config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauthes" }
  scope "(:locale)", locale: /en|vi/ do
    root "products#index"
    resources :products, only: %i(index show) do
      resources :comments
    end

    resource :cart, only: %i(show create destroy update)
    resources :orders, only: %i(create show index) do
      member do
        patch "/cancel", to: "orders#cancel"
      end
    end
    devise_for :accounts, controllers: { sessions: "sessions", registrations: "accounts" }, skip: :omniauth_callbacks
    namespace :admin do
      resources :products
      resources :users
      resources :orders
      get "/statistics", to: "statistics#monthly_statistics", as: "monthly_statistics"
      get "/statistics/:month/:year", to: "statistics#monthly_statistics_detail", as: "monthly_statistics_detail"
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t("the_form_contains", num: object.errors.count) %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter.html.erb
<%= form_for :search, method: :get do |f| %>
  <div class="filter ">
    <div class="mb-3 d-flex align-items-center">
      <%= f.label :category_id_eq, t("products.filter.brand"), class: "form-label mt-1 me-2" %>
      <%= f.select :category_id_eq, options_for_select(all_select_of_category, selected: params.dig(:search, :category_id_eq) ? params.dig(:search, :category_id_eq) : "" ), class: "form-select" %>
    </div>

    <div class="mb-3 d-flex align-items-center">
      <%= f.label :price_between, t("products.filter.price"), class: "form-label mt-1 me-2" %>
      <%= f.select :price_between, options_for_select(all_select_price_search_product, selected: params.dig(:search, :price_between) ? params.dig(:search, :price_between) : "" ), class: "form-select" %>
    </div>

    <div class="mb-3 d-flex align-items-center">
      <%= f.select :created_at_year_lteq, options_for_select(all_select_year_product, selected: params.dig(:search, :created_at_year_lteq) ? params.dig(:search, :created_at_year_lteq) : Time.current.year ), class: "form-select" %>
    </div>

    <div class="mb-3 d-flex flex-column justify-content-center mt-2">
      <%= f.button :quantity_gt, value: 0, class:"mb-2 btn btn-primary" do %>
        <%= t("products.filter.title") %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to t("default_title"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to t("header.home"), root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("header.cart"), cart_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to t("header.account"), "", class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: {toggle: "dropdown", target: "#navbarDropdown"}, aria: {haspopup: "true", expanded: "false"} %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to t("header.profile"), "#", class: "dropdown-item" %>
              <% if can? :manage, :all %>
                <%= link_to t("header.admin"), admin_products_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to t("header.order"), orders_path, class: "dropdown-item" %>
              <%= link_to t("header.log_out"), destroy_account_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"></li>
            <%= link_to t("header.home"), root_url, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("header.cart"), cart_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("header.login"), new_account_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<br>
<br>
<br>

app/views/shared/_list_categories.html.erb
<div class="col-md-3 menu">
  <ul class="list-group">
    <li class="list-group-item"><a href="#"><%= t("categories.laptop")%></a></li>
    <li class="list-group-item"><a href="#"><%= t("categories.tablet")%></a></li>
    <li class="list-group-item"><a href="#"><%= t("categories.phone")%></a></li>
    <li class="list-group-item"><a href="#"><%= t("categories.pc")%></a></li>
  </ul>
</div>

app/views/shared/_search.html.erb
<%= form_for :search, class: "search-form", method: :get do |f| %>
  <div class="input-group">
    <%= f.search_field :name_or_description_or_category_name_cont, value: params.dig(:search, :name_or_description_or_category_name_cont), class: "form-control", placeholder: t("input.search") %>
    <%= f.submit t("button.search"), class: "btn" %>
  </div>
<% end %>