config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauthes" }
  scope "(:locale)", locale: /en|vi/ do
    root "products#index"
    resources :products, only: %i(index show) do
      resources :comments
    end

    resource :cart, only: %i(show create destroy update)
    resources :orders, only: %i(create show index) do
      member do
        patch "/cancel", to: "orders#cancel"
      end
    end
    devise_for :accounts, controllers: { sessions: "sessions", registrations: "accounts" }, skip: :omniauth_callbacks
    namespace :admin do
      resources :products
      resources :users
      resources :orders
      get "/statistics", to: "statistics#monthly_statistics", as: "monthly_statistics"
      get "/statistics/:month/:year", to: "statistics#monthly_statistics_detail", as: "monthly_statistics_detail"
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  QUANTITY = "quantity".freeze

  has_many :comments, dependent: :destroy
  has_many :order_histories, dependent: :restrict_with_error
  belongs_to :category
  has_many :orders, through: :order_histories
  has_many :accounts, through: :comments

  has_one_attached :image do |attachable|
    attachable.variant(:display, resize_to_limit: Settings.SIZE_224x224)
  end

  scope :price_sort, -> { where(is_deleted: false).order(price: :desc) }
  scope :product_outstanding, (lambda do
                                 select("products.*, SUM(order_histories.quantity) AS total_quantity")
                                 .joins(:order_histories)
                                 .group("products.id")
                                 .order("total_quantity DESC")
                                 .joins("INNER JOIN orders ON orders.id = order_histories.order_id")
                                 .where(orders: { status: Order.statuses[:approved] })
                                 .where(is_deleted: false)
                                 .limit(Settings.DIGIT_10)
                               end)

  validates :name, presence: true, length: { maximum: Settings.DIGIT_255 }
  validates :price, presence: true, numericality: true
  validates :description, presence: true, length: { maximum: Settings.DIGIT_1000 }
  validates :quantity, presence: true, numericality: true, length: { maximum: Settings.DIGIT_1000 }

  ransacker :created_at_year do
    Arel::Nodes::SqlLiteral.new("year(products.created_at)")
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at_year description name price quantity created_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category]
  end

  delegate :name, to: :category, prefix: true

  def refund_quantity(quantity)
    return if update(quantity: self.quantity + quantity)

    raise(ActiveRecord::Rollback)
  end

  def delete_soft
    return false if orders.exists?(status: Order.statuses[:pending])

    update_columns(is_deleted: true)
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::AdminController
  load_and_authorize_resource
  skip_load_resource only: %i(index new create)

  def index
    @pagy, @products = pagy(Product.ransack(params[:search]).result, items: Settings.DIGIT_5)
    @top_10_outstanding ||= Product.product_outstanding
  end

  def edit; end

  def new
    @product = Product.new
  end

  def update
    if @product.update(product_params)
      flash[:admin_success] = t("admin.products.update.success")
      redirect_to(admin_products_path)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:admin_success] = t("admin.products.create.success")
      redirect_to(admin_products_path)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def destroy
    if @product.delete_soft
      flash[:admin_success] = t("admin.products.delete.success")
    else
      flash[:admin_error] = t("admin.products.delete.fail")
    end
    redirect_to(admin_products_path)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :category_id, :image, :description)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  load_resource only: :show
  authorize_resource only: %i(index show)
  before_action :show_slider, only: %i[index show]
  before_action :load_categories, only: :index

  def index
    @pagy, @products = pagy(Product.ransack(params[:search]).result.price_sort, items: Settings.PAGE_9)
    @product_outstandings = Product.product_outstanding
  end

  def show; end

  private

  def load_categories
    @categories = Category.pluck(:name, :id).map { |category| [category[0], category[1]] }
  end

  def show_slider
    @slider = params[:search].blank? && params[:category_id].blank? && params[:price_range].blank?
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def product_image_tag(product)
    if product.image.attached?
      image_tag(product.image.variant(:display), class: "product-image", alt: product.name)
    else
      image_tag(Settings.NO_IMAGE, class: "product-image")
    end
  end

  def render_comments(comments)
    if comments.present?
      render(partial: "products/comment", locals: { comments: comments })
    else
      content_tag(:p, t("products.no_comment"))
    end
  end

  def all_select_year_product
    [
      [t("products.filter.newest"), Time.current.year],
      [t("products.filter.hoting"), Time.current.year - 1],
      [t("products.filter.lowering_prices"), Time.current.year - 2]
    ]
  end

  def all_select_price_search_product
    [
      [t("products.filter.all"), ""],
      [t("products.filter.range_5_to_10"), Settings.range_5m_to_10m],
      [t("products.filter.range_10_to_20"), Settings.range_10m_to_20m],
      [t("products.filter.range_20_to_50"), Settings.range_20m_to_50m],
      [t("products.filter.range_50_to_100"), Settings.range_50m_to_100m]
    ]
  end
end

app/views/admin/products/_form.html.erb
<%= f.label :name, t("admin.products.name"), class:"mt-3" %>
<%= f.text_field :name, class:"mt-1 w-100" %>
<h5 class="text-danger mt-2 w-100 text-center fs-6"><%=  @product.errors.messages[:name][0] if @product.errors.messages[:name][0] %></h5>
<%= f.label :category, t("admin.products.category"), class:"mt-1" %>
<%= image_tag(@product.image.variant(:display), class: "w-25 h-25" ) if @product.image.present? %>
<%= f.file_field :image, accept: "image/png,image/jpeg" %>
<br/>
<%= f.select :category_id, options_for_select(all_select_of_category, selected: @product.category_id), class:"mt-1" %>
<br/>
<%= f.label :price, t("admin.products.price"), class:"mt-1" %>
<%= f.text_field :price, class:"mt-1 w-100" %>
<h5 class="text-danger mt-2 w-100 text-center fs-6"><%=  @product.errors.messages[:price][0] if @product.errors.messages[:price][0] %></h5>
<%= f.label :quantity, t("admin.products.quantity"), class:"mt-1" %>
<%= f.text_field :quantity, class:"mt-1 w-100" %>
<h5 class="text-danger mt-2 w-100 text-center fs-6"><%= @product.errors.messages[:quantity][0] if @product.errors.messages[:quantity][0] %></h5>
<%= f.label :description, t("admin.products.description"), class:"mt-1" %>
<%= f.text_area :description, class:"mt-1 w-100" %>
<h5 class="text-danger mt-2 w-100 text-center fs-6"><%= @product.errors.messages[:description][0] if @product.errors.messages[:description][0] %></h5>
<%= f.submit class:"mt-3"%>

app/views/admin/products/_product.html.erb
<tr style="display:flex; align-items:center; margin-top:10px">
  <td class="sizing-table-first-column text-center">
    <%= product_counter + 1 %>
  </td>
  <td class="sizing-table text-center">
    <%= product.name %>
  </td>
  <td class="sizing-table text-center">
    <%= product.category.name %>
  </td>
  <td class="sizing-table text-center">
    <%= number_to_currency(product.price, precision: 0) %>
  </td>
  <td class="sizing-table text-center">
    <%= product.quantity %>
  </td>
  <td class="sizing-table text-center">
    <% if @top_10_outstanding.include?(product) %>
      <i class="bi bi-bookmark-check bg-success bg-gradient fw-bold text-white p-1 rounded"></i>
    <% else %>
      <i class="bi bi-bookmark-x bg-danger bg-gradient fw-bold text-white p-1 rounded"></i>
    <% end %>
  </td>
  <td class="sizing-table justify-content-center d-flex align-items-center">
    <%= link_to edit_admin_product_path(product) do %>
      <i class="bi bi-pen bg-warning bg-gradient fw-bold text-white rounded p-1"></i>
    <% end %>
    <%= form_for(:product, url: admin_product_path(product), method: :delete) do |f| %>
        <%= f.button "", data: { "turbo-method": :delete,turbo_confirm: t("sure") }, class:"button-trash" do %>
          <i class="bi bi-trash bg-danger bg-gradient fw-bold text-white p-1 rounded "></i>
        <% end %>
      <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<div class="d-flex container-admin">
  <%= render "admin/layouts/sidebar" %>
  <aside class="col-md-10 ms-5" id="main" >
    <div class="d-flex align-items-center">
      <h2><%= t("admin.products.title") %></h2>
    </div>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= form_for :product, url: admin_product_path(@product), method: :put, class: "d-flex flex-column" do |f| %>
          <%= render "form" , f: f %>
        <% end %>
      </div>
    </div>
  </aside>
</div>

app/views/admin/products/index.html.erb
<div class="d-flex container-admin">
  <%= render "admin/layouts/sidebar" %>
  <aside class="col-md-10 ms-5" id="main" >
    <div class="d-flex align-items-center mt-3">
      <h2><%= t("admin.products.title") %></h2>
      <%= link_to  new_admin_product_path, id:"addButton", class:"open-modal main-top-btn-add text-white fw-bold d-flex align-items-center ms-3" do%>
        <i class="bi bi-plus fw-bold fs-3 me-1" ></i> <%= t("admin.products.insert")%>
      <% end %>
    </div>
    <h5 class="mt-5"><%= t("admin.products.list_title", num: @products.count)%></h5>
    <hr/>
    <div>
      <div class="d-flex">
        <div class="container-main-mid-search">
          <%= form_for(:search, method: :get) do |f| %>
            <%= f.text_field :name_or_description_or_category_name_cont, value: params.dig(:search, :name_or_description_or_category_name_cont), placeholder: "Search by name, description", class:"ps-3 pe-3" %>
            <%= f.button  class: "p-2 pe-4 ps-4 text-center " do %>
              <i class="bi bi-search text-black"></i>
            <% end %>
          <% end %>
        </div>
        <%= link_to "#", class:"ms-3 main-top-btn-add text-white bg-danger bg-gradient fw-bold d-flex align-items-center" do %>
          <%= t("admin.products.remove_all")%>
        <% end %>
      </div>
      <div id="admin_error_explanation" class="w-100 d-flex justify-content-center mt-5">
        <%= render "admin/layouts/flash_admin" %>
        <%= render "layouts/flash" %>
      </div>
        <table class="mt-5 mb-5 table-products table table-striped ">
          <thead>
            <tr class="d-flex">
              <th class="sizing-table-first-column text-center"><%= t("admin.products.ordinal_number") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.name") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.producer") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.price") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.quantity") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.outstanding") %></th>
              <th class="sizing-table text-center"><%= t("admin.products.action") %></th>
            </tr>
          </thead>
          <tbody>
            <%= render(@products) || t("admin.products.empty") %>
          </tbody>

        </table>
         <div class = "d-flex justify-content-center"><%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %><div>
    </div>
  </aside>
</div>
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t("admin.products.title") %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="d-flex container-admin">
  <%= render "admin/layouts/sidebar" %>
  <aside class="col-md-10 ms-5" id="main" >
    <div class="d-flex align-items-center">
      <h2><%= t("admin.products.title") %></h2>
    </div>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= form_for :product, url: admin_products_path, class: "d-flex flex-column" do |f| %>
          <%= render "form", f: f %>
        <% end %>
      </div>
    </div>
  </aside>
</div>