config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauthes" }
  scope "(:locale)", locale: /en|vi/ do
    root "products#index"
    resources :products, only: %i(index show) do
      resources :comments
    end

    resource :cart, only: %i(show create destroy update)
    resources :orders, only: %i(create show index) do
      member do
        patch "/cancel", to: "orders#cancel"
      end
    end
    devise_for :accounts, controllers: { sessions: "sessions", registrations: "accounts" }, skip: :omniauth_callbacks
    namespace :admin do
      resources :products
      resources :users
      resources :orders
      get "/statistics", to: "statistics#monthly_statistics", as: "monthly_statistics"
      get "/statistics/:month/:year", to: "statistics#monthly_statistics_detail", as: "monthly_statistics_detail"
    end
  end
end

app/views/admin/layouts/_flash_admin.html.erb
<% if flash.present? %>
  <% case %>
    <% when flash[:admin_success] %>
      <div class="alert alert-success mt-3 w-50 text-center">
        <%= flash[:admin_success] %>
      </div>
    <% when flash[:admin_error] %>
      <div class="alert alert-warning mt-3 w-50 text-center">
        <%= flash[:admin_error] %>
      </div>
       <% when flash[:admin_danger] %>
      <div class="alert alert-danger mt-3 w-50 text-center">
        <%= flash[:admin_danger] %>
      </div>
  <% end %>
<% end %>

app/views/admin/layouts/_sidebar.html.erb
  <aside class="col-md-2 bg-success text-center">
    <div class="container-profile">
      <%= image_tag("https://e7.pngegg.com/pngimages/571/845/png-clipart-chibi-anime-drawing-female-chibi-white-mammal-thumbnail.png", class:"w-50 h-50 imgae_profile mt-3")%>
      <h5 class="text-white mt-3"><%= current_account.name%></h5>
    </div>
    <hr/>
    <div class= "d-flex flex-column align-items-center">
      <%= link_to admin_products_path, class:"nav-selection bg-secondary" do %>
       <%= t("products.title") %>
      <% end %>
      <%= link_to admin_orders_path, class:"nav-selection bg-secondary" do %>
       <%= t("orders.title") %>
      <% end %>
      <% if can? :access_denied, :controller %>
        <%= link_to admin_monthly_statistics_path, class:"nav-selection bg-secondary" do %>
          <%= t("admin.statistics.title") %>
        <% end %>
      <% end%>
    </div>
  </aside>