config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauthes" }
  scope "(:locale)", locale: /en|vi/ do
    root "products#index"
    resources :products, only: %i(index show) do
      resources :comments
    end

    resource :cart, only: %i(show create destroy update)
    resources :orders, only: %i(create show index) do
      member do
        patch "/cancel", to: "orders#cancel"
      end
    end
    devise_for :accounts, controllers: { sessions: "sessions", registrations: "accounts" }, skip: :omniauth_callbacks
    namespace :admin do
      resources :products
      resources :users
      resources :orders
      get "/statistics", to: "statistics#monthly_statistics", as: "monthly_statistics"
      get "/statistics/:month/:year", to: "statistics#monthly_statistics_detail", as: "monthly_statistics_detail"
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  QUANTITY = "quantity".freeze

  has_many :comments, dependent: :destroy
  has_many :order_histories, dependent: :restrict_with_error
  belongs_to :category
  has_many :orders, through: :order_histories
  has_many :accounts, through: :comments

  has_one_attached :image do |attachable|
    attachable.variant(:display, resize_to_limit: Settings.SIZE_224x224)
  end

  scope :price_sort, -> { where(is_deleted: false).order(price: :desc) }
  scope :product_outstanding, (lambda do
                                 select("products.*, SUM(order_histories.quantity) AS total_quantity")
                                 .joins(:order_histories)
                                 .group("products.id")
                                 .order("total_quantity DESC")
                                 .joins("INNER JOIN orders ON orders.id = order_histories.order_id")
                                 .where(orders: { status: Order.statuses[:approved] })
                                 .where(is_deleted: false)
                                 .limit(Settings.DIGIT_10)
                               end)

  validates :name, presence: true, length: { maximum: Settings.DIGIT_255 }
  validates :price, presence: true, numericality: true
  validates :description, presence: true, length: { maximum: Settings.DIGIT_1000 }
  validates :quantity, presence: true, numericality: true, length: { maximum: Settings.DIGIT_1000 }

  ransacker :created_at_year do
    Arel::Nodes::SqlLiteral.new("year(products.created_at)")
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at_year description name price quantity created_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category]
  end

  delegate :name, to: :category, prefix: true

  def refund_quantity(quantity)
    return if update(quantity: self.quantity + quantity)

    raise(ActiveRecord::Rollback)
  end

  def delete_soft
    return false if orders.exists?(status: Order.statuses[:pending])

    update_columns(is_deleted: true)
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::AdminController
  load_and_authorize_resource
  skip_load_resource only: %i(index new create)

  def index
    @pagy, @products = pagy(Product.ransack(params[:search]).result, items: Settings.DIGIT_5)
    @top_10_outstanding ||= Product.product_outstanding
  end

  def edit; end

  def new
    @product = Product.new
  end

  def update
    if @product.update(product_params)
      flash[:admin_success] = t("admin.products.update.success")
      redirect_to(admin_products_path)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:admin_success] = t("admin.products.create.success")
      redirect_to(admin_products_path)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def destroy
    if @product.delete_soft
      flash[:admin_success] = t("admin.products.delete.success")
    else
      flash[:admin_error] = t("admin.products.delete.fail")
    end
    redirect_to(admin_products_path)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :category_id, :image, :description)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  load_resource only: :show
  authorize_resource only: %i(index show)
  before_action :show_slider, only: %i[index show]
  before_action :load_categories, only: :index

  def index
    @pagy, @products = pagy(Product.ransack(params[:search]).result.price_sort, items: Settings.PAGE_9)
    @product_outstandings = Product.product_outstanding
  end

  def show; end

  private

  def load_categories
    @categories = Category.pluck(:name, :id).map { |category| [category[0], category[1]] }
  end

  def show_slider
    @slider = params[:search].blank? && params[:category_id].blank? && params[:price_range].blank?
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def product_image_tag(product)
    if product.image.attached?
      image_tag(product.image.variant(:display), class: "product-image", alt: product.name)
    else
      image_tag(Settings.NO_IMAGE, class: "product-image")
    end
  end

  def render_comments(comments)
    if comments.present?
      render(partial: "products/comment", locals: { comments: comments })
    else
      content_tag(:p, t("products.no_comment"))
    end
  end

  def all_select_year_product
    [
      [t("products.filter.newest"), Time.current.year],
      [t("products.filter.hoting"), Time.current.year - 1],
      [t("products.filter.lowering_prices"), Time.current.year - 2]
    ]
  end

  def all_select_price_search_product
    [
      [t("products.filter.all"), ""],
      [t("products.filter.range_5_to_10"), Settings.range_5m_to_10m],
      [t("products.filter.range_10_to_20"), Settings.range_10m_to_20m],
      [t("products.filter.range_20_to_50"), Settings.range_20m_to_50m],
      [t("products.filter.range_50_to_100"), Settings.range_50m_to_100m]
    ]
  end
end

app/views/products/_comment.html.erb
<% comments.each do |comment| %>
  <div class="comment">
    <%= comment.account.name %>
    <div class="product-rating">
      <% rating = comment.rating ||= 0 %>
      <% Settings.DIGIT_5.times do |i| %>
        <% if rating >= i + 1 %>
          <i class="bi bi-star-fill" style="color: yellow;"></i>
        <% else %>
          <i class="bi bi-star" style="color: yellow;"></i>
        <% end %>
      <% end %>
      <span>(<%= rating %>)</span>
    </div>
    <%= comment.content ||= "" %>
  </div>
<% end %>

app/views/products/_outstanding_product.html.erb
<div class="swiper">
  <div class="swiper-wrapper">
    <% @product_outstandings.each do |product| %>
      <div class="swiper-slide d-flex justify-content-center">
        <div class="col-md-4 w-100">
          <div class="product-item-container">
            <div class="product-item-info">
              <%= product_image_tag(product) %>
              <h4><%= link_to product.name, product_path(product) %></h4>
               <div class="product-rating">
                  <% if product && product.comments.present? %>
                    <% rating = product.comments.average(:rating).to_f.round(2) %>
                  <% else %>
                    <% rating = 0 %>
                  <% end %>
                  <% Settings.DIGIT_5.times do |i| %>
                    <% if rating >= i + 1 %>
                      <i class="bi bi-star-fill" style="color: yellow;"></i>
                    <% else %>
                      <i class="bi bi-star" style="color: yellow;"></i>
                    <% end %>
                  <% end %>
                  <span>(<%= rating %>)</span>
                </div>
              <p><%= number_to_currency(product.price, precision: 0) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col-md-4 my-3">
  <div class="card">
    <%= product_image_tag(product) %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to product.name, product_path(product) %></h5>
      <div class="product-rating">
        <% if product && product.comments.present? %>
          <% rating = product.comments.average(:rating).to_f.round(2) %>
        <% else %>
          <% rating = 0 %>
        <% end %>
        <% Settings.DIGIT_5.times do |i| %>
          <% if rating >= i + 1 %>
            <i class="bi bi-star-fill" style="color: yellow;"></i>
          <% else %>
            <i class="bi bi-star" style="color: yellow;"></i>
          <% end %>
        <% end %>
        <span>(<%= rating %>)</span>
      </div>
      <p><%= number_to_currency(product.price*1000000, precision: 0) %></p>
      <% if account_signed_in? %>
        <div class="add-to-cart">
          <%= button_to t("products.add_to_cart"), cart_path(product_id: product.id), method: :post, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% provide :title, t("header.home") %>
<div class="container">
  <%= render "shared/search" %>
</div>
<div class="container content text-center">
  <% if flash %>
    <%= render "layouts/flash" %>
  <% end %>
  <% if @slider %>
    <%= render "outstanding_product" %>
  <% end %>
  <div class="row">
    <%= render "shared/list_categories" %>
    <div class="col-md-9 justify-content-center">
      <%= render "shared/filter" %>
      <div class="row">
        <% @products.each do |product| %>
          <%= render partial: "products/product", locals: { product: product } %>
        <% end %>
        <%= t("products.empty") if @products.empty? %>
      </div>
      <div class="pagination justify-content-center">
        <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container content text-center">
  <div class="row justify-content-between">
    <%= render "shared/list_categories" %>
    <div class="col-md-9">
      <%= product_image_tag(@product) %>
      <h1><%= @product.name %></h1>
          <div class="product-rating">
            <% if @product && @product.comments.present? %>
              <% rating = @product.comments.average(:rating).to_f.round(2) %>
            <% else %>
              <% rating = 0 %>
            <% end %>
            <% Settings.DIGIT_5.times do |i| %>
              <% if rating >= i + 1 %>
                <i class="bi bi-star-fill" style="color: yellow;"></i>
              <% else %>
                <i class="bi bi-star" style="color: yellow;"></i>
              <% end %>
            <% end %>
            <span>(<%= rating %>)</span>
          </div>
      <p><%= t("products.price", price: number_to_currency(@product.price)) %></p>
      <p><%= t("products.quantity", quantity: @product.quantity) %></p>
      <div class="add-to-cart">
        <%= button_to t("products.add_to_cart"), cart_path(product_id: @product.id), method: :post %>
      </div>
      <div class="product-info">
        <div class="product-description">
          <strong><%= t("products.description_title") %></strong>
          <p><%= @product.description %></p>
        </div>
        <div class="product-comment">
          <strong><%= t("products.comments_title") %></strong>
          <%= render_comments(@product.comments) %>
        </div>
      </div>
    </div>
  </div>
</div>